server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:              
              searchLocations: classpath:config/, classpath:config/wiki
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}    

