server:
  port: 9411
  
spring:
  application:
    name: zipkin
  cloud:
    config:
      uri: http://localhost:8888/
   
  sleuth:
      enabled: true  
  zipkin:
    storage.type: mem  
    
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
    ddl-auto: none

 
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
    
hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true 
    