server:
  port: 8083
  
spring:
  application:
    name: turbine
      
turbine:
 aggregator:
   cluster-config: default
app-config: wiki
cluster-name-expression: new String("default")
combine-host-port: true
instanceUrlSuffix.default: actuator/hystrix.stream

eureka:
  instance:
   prefer-ip-address: true  
   leaseRenewalIntervalInSeconds: 3
   leaseExpirationDurationInSeconds: 3   
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  cloud:
    config:
      uri: http://localhost:8888
    discovery:
        enabled: true       