server:
  port: 8082

spring:
  application:
    name: hystrix
  
feign:
 hystrix:
  enabled: true

eureka:
  instance:
   prefer-ip-address: true  
   leaseRenewalIntervalInSeconds: 3
   leaseExpirationDurationInSeconds: 3 
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  cloud:
    config:
      uri: http://localhost:8888
    discovery:
        enabled: true
